---
blank_issues_enabled: false

contact_links:
  - name: "üìñ –î–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è"
    url: "https://github.com/v-shub/students-on-duty/docs/dev/development-process.md"
    about: "–ü—Ä–æ—á—Ç–∏—Ç–µ –ø–µ—Ä–µ–¥ —Å–æ–∑–¥–∞–Ω–∏–µ–º Issue"
  - name: "üí¨ –í–æ–ø—Ä–æ—Å—ã"
    url: "https://github.com/v-shub/students-on-duty/discussions"
    about: "–ó–∞–¥–∞–≤–∞–π—Ç–µ –≤–æ–ø—Ä–æ—Å—ã –≤ Discussions"